# Generated by Django 6.0.1 on 2026-01-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='income_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_customer',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
