# Generated by Django 6.0.1 on 2026-01-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_insurance_income_loss_alter_customer_id_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('C&I', 'C&I')], max_length=20, null=True),
        ),
    ]
